### PR TITLE
Using Google Sheets to help build Docs

### PR DESCRIPTION
**Pull request by linoxyn**
For your consideration I have added some information in `sheets.md` for users of your `gatsby-source-google-docs` to help people get started and learn about using **Google Sheets** in their project.

### CODE REVIEW

**Review by cedricdelpoux — APPROVED** [review]

**Comment by cedricdelpoux** [comment]
Thank you! You are very helpful. 
Following the conversation in #71 , I used Google Script to build the site clicking a button in my Google Sheet. It is great! Do you use something like that?

Later I would like to improve this part. I also thinked about a Google Doc/Sheet Addon to make it easier to use

**Comment by linoxyn** [comment]
Thank you! 

I use the **Sheets** to easily build the needed **Docs** which supplies the needed data for your `gatsby-source-google-docs` plugin. The**Docs** are also easy for the client to edit text and images as they need.

I have a [dummy site](https://secret-beacon-274315.web.app/) (to test cloud handling of form submissions) built using `firebase-cli` within the project. **Google Firebase** where I have used **Cloud Firebase Functions** , **Storage**, **Realtime Database**, and **Firebase Hosting**. I have not yet hooked things up yet to deploy though I hope to use **Google Cloud Build** and **Run** to allow the client to update their site after changes and additions are made. 

You wrote: *I used Google Script to build the site clicking a button in my Google Sheet.*

Were you able to write code to trigger a `gatsby build`? and also deploy to hosting? I'm not sure if that's what you meant?

**Comment by cedricdelpoux** [comment]
I'm not sure to understand the need to add images in a google Sheet because you can add all images you want in a document. Could you share Google sheet and your Google Script to help me understand what you are achieving with it? I could improve the doc when I understood better your process.

Personally, I add metadata directly into Google drive description field. But I think you don't want to ask it to do so to your clients, right?

Yes, I create a simple sheet with a button and when I click it, Gatsby Cloud build the site

**Comment by linoxyn** [comment]
@cedricdelpoux  yes, I agree that it's not best to add the url for the image in the sheets. I works for some uses, like products that contain one or more images that are mapped into a component through a graphql query on *images* , though now I have actually taken this out of all my **sheets** for the project except for an external email receipt for a commission acceptance generated by the **app script**. 

### For the Description Field
I assign a value for each row data value in an `SpreadsheetApp.getActiveSpreadsheet().getActiveSheet().getActiveRange().getDisplayValues()` making sure that the row or rows  length, start index, and range is stored, any of these values can be pass into the *description* as `YAML` in the newly created **Doc** as:

```
const newDoc = DriveApp.getFileById(documentId);

newDoc.setDescription(`page: ${page}
prodtitle: ${title)
fullname: ${fullname}
lastname: ${last}
year: ${year}
price: ${price}
sold: ${sold}
category: ${category}
exceptional: ${exceptional}`);

```

I hope that helps explain more? Let me know if you need a longer explanation and more of a code example?

I am curious as to what you are invoking to trigger a `build` on Gatsby Cloud? Are you able to reference a change to a repository or just on a change to or creation of a **Doc**, or maybe it's just a function call? I am wondering if Gatsby Cloud may be a better `build` solution if I ever get this project off the ground LOL 

Thanks for your help!

**Comment by cedricdelpoux** [comment]
I understand globally what you achieve but it hard to imagine how everything work.

I do think I can help adding more feature to this plugin for an usecase.

Could you create an example repo using the minimum dependencies using some`Google sheets` and `Google scripts`? I understand you don't want to share your files publicly. If so, you can email me the urls to these files.

**Pull request merged**
