### PR TITLE
fix: handle empty content for getTableCellContent

### PR DESCRIPTION
**Pull request by AlberErre**
Handles build error for empty content on table cells

Details for this fix on #149

### CODE REVIEW

**Comment by AlberErre** [comment]
@cedricdelpoux the CI is failing due to `yarn --frozen-lockfile` issue. Looks like it has been failing for the previous PRs too.

Is there anything we can help with?

Thanks!

**Comment by cedricdelpoux** [comment]
Thanks for the PR. I can't bump dependencies right know to see if it resolves CI but I will do as soon as possible.

**Comment by cedricdelpoux** [comment]
I don't have my computer to release a new version but I will do it in few days. Thanks

**Comment by cedricdelpoux** [comment]
I just saw that there is un uncovered line now when running tests.

Capture d’écran 2022-01-29 à 09 39 33

If you get the extra motivation, please try to cover it 😊

I just published `2.2.1` version with your fix

**Comment by cedricdelpoux** [comment]
I fixed the CI too

**Pull request merged**
